server:
  port: 8080
spring:
  application:
    name: hystrix-client
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

turbine:
  instanceInsertPort: false

  #aggregator:   
    #clusterConfig: hystrix-client  #turbine监控的服务名称，可以多个

  appConfig: hystrix-client  #turbine监控的服务，可以有多个
  clusterNameExpression: "'default'"